const fs = require("fs");
const path = require("path");

const buildDir = path.join(__dirname, "..", "build");
const pkg = require("../package.json");

function publicPath() {
  const fromEnv = process.env.PUBLIC_URL;
  const raw = fromEnv != null && fromEnv !== "" ? fromEnv : pkg.homepage || "/";
  if (raw === "." || raw === "") return "";
  if (raw.startsWith("/")) return raw.replace(/\/$/, "");
  try {
    return new URL(raw).pathname.replace(/\/$/, "");
  } catch (err) {
    return "";
  }
}

function walk(dir, prefix) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(full, rel) : [rel];
  });
}

function ignored(rel) {
  return (
    rel === "service-worker.js" ||
    rel.endsWith(".map") ||
    rel.endsWith(".zip") ||
    rel.endsWith(".LICENSE.txt")
  );
}

const prefix = publicPath();
const urls = walk(buildDir)
  .filter((rel) => !ignored(rel))
  .map((rel) => {
    const joined = `${prefix}/${rel}`.replace(/\/{2,}/g, "/");
    return joined.startsWith("/") ? joined : `/${joined}`;
  });

const fallback = (`${prefix}/index.html`).replace(/\/{2,}/g, "/");
const source = `/* generated by scripts/build-sw.js — do not edit */
const CACHE = ${JSON.stringify("mdwa-v6-" + Date.now())};
const URLS = ${JSON.stringify(urls)};
const FALLBACK = ${JSON.stringify(fallback.startsWith("/") ? fallback : "/" + fallback)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(URLS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  if (event.request.method !== "GET") return;
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request)
        .then((response) => {
          if (response && response.ok && response.type === "basic") {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(event.request, copy));
          }
          return response;
        })
        .catch(() => (event.request.mode === "navigate" ? caches.match(FALLBACK) : undefined));
    })
  );
});
`;

fs.writeFileSync(path.join(buildDir, "service-worker.js"), source);
console.log(`service-worker.js cached ${urls.length} files with prefix "${prefix || "/"}"`);
